<a href="https://colab.research.google.com/github/mssnowy/pro115/blob/main/p115_TEXT_PRE_PROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/procodingclass/product_dataset.git

Cloning into 'product_dataset'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), 3.08 MiB | 11.38 MiB/s, done.


In [ ]:
# Make a dataframe using the 'pandas' module
import pandas as pd
dataframe = pd.read_excel('/content/product_dataset/updated_product_dataset.xlsx')
#print(dataframe.head())
dataframe.head()

Emotion                                               Text
0  Positive  close approximation red octane mat bought one ...
1   Neutral  little lumpy mat great foam padding it’s use...
2  Positive  great pad love ddr not want metal pad get work...
3  Positive  excellent pad great product highly responsive ...
4  Positive  awesome great ddr pad works perfectly pc stepm...

In [ ]:
dataframe["Emotion"].unique()

array(['Positive', 'Neutral', 'Negative'], dtype=object)

In [ ]:
encode_product={"Positive":0,"Neutral":1,"Negative":2}

In [ ]:
dataframe.replace(encode_product,inplace=True)

In [ ]:
dataframe.head()

Emotion                                               Text
0        0  close approximation red octane mat bought one ...
1        1  little lumpy mat great foam padding it’s use...
2        0  great pad love ddr not want metal pad get work...
3        0  excellent pad great product highly responsive ...
4        0  awesome great ddr pad works perfectly pc stepm...

In [ ]:
training_sentences=[]
training_labels = []
# append text and emotions in the list using the 'loc' method
for i in range(len(dataframe)):
  sentence = dataframe.loc[i,"Text"]
  training_sentences.append(sentence)
  label = dataframe.loc[i,"Emotion"]
  training_labels.append(label)
#Check a random text and label of the list
training_sentences[50],training_labels[50]

('great game got game daughter birthday loves', 0)

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
#Define parameters for Tokenizer
vocab_size=10000
embedding_dim = 16
oov_tok = "<OOV>"
training_size = 20000
tokenizer=Tokenizer(num_words=vocab_size,oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
#Create a word_index dictionary
word_index = tokenizer.word_index
#Check the tokenized sequence
word_index["wrong"]

434

In [ ]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
print(training_sequences[0])
print(training_sequences[1])
print(training_sequences[2])

[457, 8739, 706, 8740, 3945, 38, 14, 590, 38, 150, 8741, 6115, 3945, 331, 2493, 2938, 907, 32, 182, 1695, 8742, 209, 1, 8742, 52, 3529, 507, 663, 1, 3945, 7097, 619, 1391, 1, 1072, 1007, 604, 2835, 194, 1, 340, 156, 7098, 14, 5423, 3059, 8743, 14, 5423, 1415, 2938, 1, 10, 2279, 1415, 173, 8744, 2022, 580, 41, 3190, 1331, 1415, 4926, 1237, 1173, 100, 1, 209, 908, 1, 706, 8740, 3945, 206, 134, 31, 870, 267, 753, 237, 402, 8, 734, 20, 402, 8, 922, 114, 1920, 8745, 707, 57, 1332, 1215, 2736, 20, 170, 6116, 6, 7]
[49, 8746, 3945, 2, 2938, 3529, 132, 319, 639, 458, 1972, 78, 2061, 7099, 604, 332, 3945, 8746, 4540, 3735, 291, 682, 1008, 1282, 8747, 3945, 2062, 6117, 45, 206, 9, 754, 2345, 517, 194, 43, 2155, 32, 31, 1696, 2835, 622, 363, 787, 4541, 682, 1365, 2101, 1139, 6, 7]
[2, 907, 11, 6115, 9, 94, 539, 907, 27, 20, 2, 8748]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#Define parameters for pad_sequences
padding_type = 'post'
max_length = 100
trunc_type='post'
training_padded = pad_sequences(training_sequences,maxlen=max_length, padding=padding_type,truncating=trunc_type)

#Check the padded sequence
training_padded
print(training_padded[0:3])

[[ 457 8739  706 8740 3945   38   14  590   38  150 8741 6115 3945  331
  2493 2938  907   32  182 1695 8742  209    1 8742   52 3529  507  663
     1 3945 7097  619 1391    1 1072 1007  604 2835  194    1  340  156
  7098   14 5423 3059 8743   14 5423 1415 2938    1   10 2279 1415  173
  8744 2022  580   41 3190 1331 1415 4926 1237 1173  100    1  209  908
     1  706 8740 3945  206  134   31  870  267  753  237  402    8  734
    20  402    8  922  114 1920 8745  707   57 1332 1215 2736   20  170
  6116    6]
 [  49 8746 3945    2 2938 3529  132  319  639  458 1972   78 2061 7099
   604  332 3945 8746 4540 3735  291  682 1008 1282 8747 3945 2062 6117
    45  206    9  754 2345  517  194   43 2155   32   31 1696 2835  622
   363  787 4541  682 1365 2101 1139    6    7    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0

In [ ]:
class Employee:
  def __init__(self,name,Empid):
    self.name=name
    self.Empid=Empid
    print(self.Empid)
std=Employee("Jhon",1)
std.Empid=2



1


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#Define parameters for pad_sequences
padding_type = 'post'
max_length = 100
trunc_type='post'
dataframe = pad_sequences(training_sequences,maxlen=max_length, padding=padding_type,truncating=trunc_type)

#Check the padded sequence
dataframe
print(dataframe[0:3])

[[ 457 8739  706 8740 3945   38   14  590   38  150 8741 6115 3945  331
  2493 2938  907   32  182 1695 8742  209    1 8742   52 3529  507  663
     1 3945 7097  619 1391    1 1072 1007  604 2835  194    1  340  156
  7098   14 5423 3059 8743   14 5423 1415 2938    1   10 2279 1415  173
  8744 2022  580   41 3190 1331 1415 4926 1237 1173  100    1  209  908
     1  706 8740 3945  206  134   31  870  267  753  237  402    8  734
    20  402    8  922  114 1920 8745  707   57 1332 1215 2736   20  170
  6116    6]
 [  49 8746 3945    2 2938 3529  132  319  639  458 1972   78 2061 7099
   604  332 3945 8746 4540 3735  291  682 1008 1282 8747 3945 2062 6117
    45  206    9  754 2345  517  194   43 2155   32   31 1696 2835  622
   363  787 4541  682 1365 2101 1139    6    7    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0

In [ ]:
#c115
import numpy as np
training_padded=np.array(training_padded)
print(training_padded)
training_labels=np.array(training_labels)
print(training_labels)

[[ 457 8739  706 ...  170 6116    6]
 [  49 8746 3945 ...    0    0    0]
 [   2  907   11 ...    0    0    0]
 ...
 [  15    2   15 ...    0    0    0]
 [ 132  308  369 ...    0    0    0]
 [  11   23   15 ...    0    0    0]]
[0 1 0 ... 0 1 0]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense
from tensorflow.keras.layers import Conv1D,Dropout,MaxPooling1D

model=tf.keras.Sequential([
    Embedding(vocab_size,embedding_dim,input_length=max_length),
    Dropout(0.2),

    Conv1D(filters=256,kernel_size=3,activation="relu"),
    MaxPooling1D(pool_size=3),

    Conv1D(filters=128,kernel_size=3,activation="relu"),
    MaxPooling1D(pool_size=3),

    LSTM(128),
    Dense(128,activation="relu"),
    Dropout(0.2),
    Dense(64,activation='relu'),
    Dense(6,activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 16)           160000    
                                                                 
 dropout (Dropout)           (None, 100, 16)           0         
                                                                 
 conv1d (Conv1D)             (None, 98, 256)           12544     
                                                                 
 max_pooling1d (MaxPooling1D  (None, 32, 256)          0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 30, 128)           98432     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 10, 128)          0         
 1D)                                                    

In [ ]:
num_epochs=5
history=model.fit(training_padded,training_labels,epochs=num_epochs,verbose=2)

Epoch 1/5
671/671 - 46s - loss: 0.3372 - accuracy: 0.9224 - 46s/epoch - 69ms/step
Epoch 2/5
671/671 - 35s - loss: 0.1838 - accuracy: 0.9429 - 35s/epoch - 52ms/step
Epoch 3/5
671/671 - 33s - loss: 0.1354 - accuracy: 0.9536 - 33s/epoch - 50ms/step
Epoch 4/5
671/671 - 34s - loss: 0.1109 - accuracy: 0.9606 - 34s/epoch - 50ms/step
Epoch 5/5
671/671 - 34s - loss: 0.0918 - accuracy: 0.9670 - 34s/epoch - 51ms/step


In [ ]:
model.save('Text_Emotion.h5')

In [ ]:
sentence=["great phone do buy it. it is an awesome purchase with great battery life."]
sequences=tokenizer.texts_to_sequences(sentence)

padded=pad_sequences(sequences,maxlen=max_length,padding=padding_type,truncating=trunc_type)
result=model.predict(padded)
predict_class=np.argmax(result,axis=1)
predict_class

1/1 [==============================] - 0s 27ms/step


array([0])